disabled = false
languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "@sisungo/Blog"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "sisungo"
  email = "sisungo@icloud.com"
  image = "avatar.jpg"
  imageQuality = 96
  headline = "南风知我意 吹梦到西洲"
  bio = "南风知我意 吹梦到西洲"
  links = [
    { email = "mailto:sisungo@icloud.com" },
    { link = "https://example.com/" },
    { github = "https://github.com/sisungo" },
  ]
